all:
	@cowsay "YEEEEPPAAAA !!!!"
	@sleep 1
	@vim main.c
start:
	@cowsay "Okey let\'s go, !!!!"	
	@sleep 2
	@gcc main.c libwiringPi.a
	@echo "Compilation terminer :)\n"
clean:
	@comsay "Remove File temp and more"
	@sleep 2
	@rm -rf *.out
	@echo "File temp was removed with success\n"
